apiVersion: v2
name: sample-web-app
description: A Helm chart for the Sample Web App (Echo Application)
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Gabriel Silva
keywords:
  - go
  - web
  - echo
  - kong
