apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-web-app.fullname" . }}-config
  labels:
    {{- include "sample-web-app.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.service.targetPort }}"
